@echo off
set SPRING_DATASOURCE_URL=jdbc:h2:mem:prod_support;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
set SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
set SPRING_DATASOURCE_USERNAME=sa
set SPRING_DATASOURCE_PASSWORD=
mvn spring-boot:run
