server:
  port: 8081

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      auto-startup: ${KAFKA_CONSUMER_AUTO_STARTUP:true}


prod-support:
  enabled: true
  application:
    name: payment-service
    team: payments
    description: Demo payment processing service
    environment: local
  diagnostics:
    health: true
    metrics: true
    errors: true
    dependencies: true
    max-error-retention: 100
  dependencies:
    - name: postgres-db
      type: DATABASE
      status: UP
    - name: notification-service
      type: HTTP
      status: UP
    - name: fraud-detection-api
      type: HTTP
      status: UP

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
